name: doc_service
common:
  db:
    driver: mysql
    name: test
    addr: 127.0.0.1
    port: 3306
    username: root
    password: 123qwe

pandoc:
  timeout: 300
  verbose: false
  trace: false
  dump-args: false
  ignore-args: false